import { Component, OnInit, inject } from '@angular/core'; import { FormBuilder, Validators } from '@angular/forms'; import { AdvertisementsApiService, Advertisement } from '../../../api-services/advertisements/advertisements-api.service';
@Component({selector:'app-advertisements',standalone:false,template:`<section class="page"><h1>Oglasi i slike</h1><form [formGroup]="form" (ngSubmit)="save()"><mat-form-field><mat-label>Naslov</mat-label><input matInput formControlName="title"></mat-form-field><mat-form-field><mat-label>URL slike</mat-label><input matInput formControlName="imageUrl" type="url"></mat-form-field><label>ili postavi sliku (do 5 MB) <input type="file" accept="image/jpeg,image/png,image/webp,image/gif" (change)="pick($event)"></label><button mat-raised-button color="primary" [disabled]="form.invalid || saving">{{selected?'Sačuvaj':'Dodaj oglas'}}</button><button mat-button type="button" *ngIf="selected" (click)="reset()">Odustani</button></form><mat-list><mat-list-item *ngFor="let item of items"><img matListItemAvatar [src]="item.imageUrl" [alt]="item.title"><span matListItemTitle>{{item.title}}</span><button mat-button (click)="edit(item)">Uredi</button><button mat-button color="warn" (click)="remove(item.id)">Obriši</button></mat-list-item></mat-list></section>`})
export class AdvertisementsComponent implements OnInit {
  private fb=inject(FormBuilder); private api=inject(AdvertisementsApiService); items:Advertisement[]=[]; selected?:Advertisement; image?:File; saving=false;
  form=this.fb.group({title:['',[Validators.required,Validators.maxLength(200)]],imageUrl:['',[Validators.maxLength(500),Validators.pattern(/^https?:\/\/.+/i)]]});
  ngOnInit(){this.load();} load(){this.api.getAll().subscribe(x=>this.items=x);} pick(e:Event){this.image=(e.target as HTMLInputElement).files?.[0];}
  edit(item:Advertisement){this.selected=item;this.image=undefined;this.form.patchValue(item);} reset(){this.selected=undefined;this.image=undefined;this.form.reset();}
  save(){if(this.form.invalid||(!this.image&&!this.form.value.imageUrl))return;this.saving=true;const complete=(url:string)=>{const body={title:this.form.value.title!,imageUrl:url};const req=this.selected?this.api.update(this.selected.id,body):this.api.create(body);req.subscribe({next:()=>{this.saving=false;this.reset();this.load();},error:()=>this.saving=false});};
    if(this.image)this.api.uploadImage(this.image).subscribe({next:r=>complete(r.relativeUrl),error:()=>this.saving=false});else complete(this.form.value.imageUrl!);
  }
  remove(id:number){if(confirm('Obrisati oglas?'))this.api.delete(id).subscribe(()=>this.load());}
}
