import { Component, OnInit, inject } from '@angular/core';
import { StoreApiService, PharmacyOrder } from '../../../api-services/store/store-api.service';
import { AuthFacadeService } from '../../../core/services/auth/auth-facade.service';
import { ToasterService } from '../../../core/services/toaster.service';

@Component({selector:'app-orders',standalone:false,template:`<section class="page"><h1>{{auth.isAdmin()||auth.isPharmacist()?'Narudžbe kupaca':'Moje narudžbe'}}</h1><mat-card class="order-card" *ngFor="let o of orders"><mat-card-header><mat-card-title>Narudžba #{{o.id}}</mat-card-title><mat-card-subtitle>{{o.orderedAtUtc | date:'medium'}} · {{o.status}}</mat-card-subtitle></mat-card-header><mat-card-content><p>Adresa: {{o.shippingAddress}}</p><p *ngFor="let item of o.items">{{item.name}} × {{item.quantity}} — {{item.unitPrice*item.quantity | number:'1.2-2'}} KM</p><strong>Ukupno: {{o.totalPrice | number:'1.2-2'}} KM</strong><mat-form-field *ngIf="auth.isAdmin()||auth.isPharmacist()" appearance="outline"><mat-label>Status</mat-label><mat-select [value]="o.status" (selectionChange)="update(o,$event.value)"><mat-option *ngFor="let s of statuses" [value]="s">{{s}}</mat-option></mat-select></mat-form-field></mat-card-content></mat-card><p *ngIf="!orders.length">Nema narudžbi.</p></section>`,styles:[`.order-card{max-width:850px;margin-bottom:1rem;padding:.5rem}.order-card mat-card-content p{margin:.4rem 0}.order-card mat-form-field{display:block;max-width:260px;margin-top:1rem}`]})
export class OrdersComponent implements OnInit {
  private api=inject(StoreApiService);private toaster=inject(ToasterService);auth=inject(AuthFacadeService);orders:PharmacyOrder[]=[];statuses=['Pending','Processing','Shipped','Completed','Cancelled'];
  ngOnInit(){this.load();}load(){this.api.getOrders(this.auth.isAdmin()||this.auth.isPharmacist()).subscribe({next:x=>this.orders=x,error:()=>this.toaster.error('Narudžbe nije moguće učitati.')});}
  update(o:PharmacyOrder,status:string){this.api.updateOrderStatus(o.id,status).subscribe({next:()=>{o.status=status;this.toaster.success('Status narudžbe je izmijenjen.');},error:()=>this.toaster.error('Status nije moguće izmijeniti.')});}
}
