import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { StoreApiService, Cart } from '../../../api-services/store/store-api.service';
import { ToasterService } from '../../../core/services/toaster.service';

declare const Stripe: any;

@Component({selector:'app-cart',standalone:false,template:`
<section class="page"><h1>Korpa</h1><div class="cart-layout" *ngIf="cart as c; else loading">
  <div class="cart-items"><article class="cart-item" *ngFor="let item of c.items"><img [src]="item.imageUrl" [alt]="item.name"><div class="cart-item-info"><a [routerLink]="['/product',item.productId]">{{item.name}}</a><small>{{item.unitPrice | number:'1.2-2'}} KM po komadu</small><div class="item-actions"><mat-form-field appearance="outline"><mat-label>Količina</mat-label><input matInput type="number" min="1" [max]="item.stock" [ngModel]="item.quantity" (ngModelChange)="update(item,$event)"></mat-form-field><button mat-button (click)="saveForLater(item)">{{item.savedForLater?'Vrati u korpu':'Sačuvaj za kasnije'}}</button><button mat-button color="warn" (click)="remove(item.id)">Ukloni</button></div></div><strong>{{item.lineTotal | number:'1.2-2'}} KM</strong></article>
    <p *ngIf="!c.items.length" class="empty">Korpa je prazna. <a routerLink="/catalog">Pregledaj proizvode</a></p>
  </div>
  <aside class="checkout-box"><h2>Ukupno</h2><p><span>Broj artikala</span><strong>{{c.itemCount}}</strong></p><p class="total"><span>Za plaćanje</span><strong>{{c.total | number:'1.2-2'}} KM</strong></p>
    <form [formGroup]="form" (ngSubmit)="checkout()"><mat-form-field appearance="outline"><mat-label>Adresa dostave</mat-label><textarea matInput rows="3" formControlName="address"></textarea></mat-form-field><mat-form-field appearance="outline"><mat-label>Način plaćanja</mat-label><mat-select formControlName="payment"><mat-option value="CashOnDelivery">PouzeÄ‡em</mat-option><mat-option value="Card">Kartica (Stripe test)</mat-option></mat-select></mat-form-field><div *ngIf="form.value.payment === 'Card'"><div id="stripe-card-element" class="stripe-card"></div><p *ngIf="paymentError" class="payment-error">{{paymentError}}</p><small *ngIf="intent">{{intent.amount | number:'1.2-2'}} KM</small></div><button mat-raised-button color="primary" [disabled]="!c.itemCount || form.invalid || submitting || (form.value.payment === 'Card' && !cardElement)">Potvrdi narudžbu</button></form>
  </aside>
</div><ng-template #loading><p>Učitavanje korpe...</p></ng-template></section>`,styles:[`
  .cart-layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:1.5rem;align-items:start}.cart-items,.checkout-box{padding:1.25rem;border:1px solid #dce6df;border-radius:12px;background:#fff}.cart-item{display:grid;grid-template-columns:100px minmax(0,1fr) auto;align-items:center;gap:1rem;padding:1rem 0;border-bottom:1px solid #e5ebe7}.cart-item img{width:100px;height:100px;object-fit:contain}.cart-item-info>a{color:#173e27;font-weight:700;text-decoration:none}.cart-item-info small{display:block;margin:.4rem 0;color:#536458}.item-actions{display:flex;align-items:center;flex-wrap:wrap;gap:.4rem}.item-actions mat-form-field{width:105px;margin:0}.item-actions button{font-size:.82rem}.checkout-box{position:sticky;top:1rem}.checkout-box h2{margin-top:0}.checkout-box>p{display:flex;justify-content:space-between;gap:1rem}.checkout-box .total{padding-top:1rem;border-top:1px solid #dce6df;font-size:1.15rem}.checkout-box form{display:grid;gap:.5rem}.checkout-box mat-form-field{width:100%}.checkout-box button{width:100%}.stripe-card{padding:14px;border:1px solid #a8b8ad;border-radius:6px;background:white}.payment-error{color:#b42318}.empty{padding:2rem;text-align:center}@media(max-width:900px){.cart-layout{grid-template-columns:1fr}.checkout-box{position:static}}@media(max-width:560px){.cart-item{grid-template-columns:70px 1fr}.cart-item img{width:70px;height:70px}.cart-item>strong{grid-column:2}.item-actions{align-items:flex-start}}
` ]})
export class CartComponent implements OnInit {
  private api=inject(StoreApiService);private fb=inject(FormBuilder);private toaster=inject(ToasterService);
  cart?:Cart;submitting=false;paymentError="";intent?:any;private stripe:any;cardElement:any;form=this.fb.group({address:['',[Validators.required,Validators.maxLength(1000)]],payment:['CashOnDelivery',[Validators.required]]});
  ngOnInit(){this.load();this.form.controls.payment.valueChanges.subscribe(method=>{this.destroyCard();this.paymentError="";this.intent=undefined;if(method==="Card")this.prepareCard();});}
  load(){this.api.getCart().subscribe({next:x=>this.cart=x,error:()=>this.toaster.error('Korpu nije moguće učitati.')});}
  update(item:Cart['items'][number],quantity:number){if(!Number.isInteger(quantity)||quantity<1||quantity>item.stock)return;this.api.updateCartItem(item.id,quantity,item.savedForLater).subscribe({next:x=>this.cart=x,error:()=>this.toaster.error('Količina nije dostupna.')});}
  saveForLater(item:Cart['items'][number]){this.api.updateCartItem(item.id,item.quantity,!item.savedForLater).subscribe({next:x=>this.cart=x,error:()=>this.toaster.error('Izmjena nije sačuvana.')});}
  remove(id:number){this.api.removeCartItem(id).subscribe({next:()=>this.load(),error:()=>this.toaster.error('Stavku nije moguće ukloniti.')});}
  imageFallback(event:Event){(event.target as HTMLImageElement).src="/images/product-placeholder.svg";}
  private async prepareCard(){try{if(typeof Stripe==="undefined")throw new Error("Stripe.js nije učitan.");this.api.createPaymentIntent().subscribe({next:(data:any)=>{this.intent=data;this.stripe=Stripe(data.publishableKey);this.cardElement=this.stripe.elements().create("card");setTimeout(()=>this.cardElement?.mount("#stripe-card-element"));this.cardElement.on("change",(e:any)=>this.paymentError=e.error?.message??"");},error:(e:any)=>this.paymentError=e?.error||"Stripe test plaćanje nije podešeno."});}catch(e:any){this.paymentError=e.message;}}
  private destroyCard(){try{this.cardElement?.destroy();}catch{}this.cardElement=undefined;this.stripe=undefined;}
  async checkout(){if(!this.cart?.itemCount||this.form.invalid)return;this.submitting=true;let reference:string|undefined;if(this.form.value.payment==='Card'){if(!this.intent||!this.stripe||!this.cardElement){this.submitting=false;this.paymentError='Forma za karticu nije spremna.';return;}const result=await this.stripe.confirmCardPayment(this.intent.clientSecret,{payment_method:{card:this.cardElement}});if(result.error||result.paymentIntent?.status!=='succeeded'){this.submitting=false;this.paymentError=result.error?.message||'Plaćanje nije uspješno.';return;}reference=result.paymentIntent.id;}this.api.checkout(this.form.value.address!,this.form.value.payment!,reference).subscribe({next:order=>{this.submitting=false;this.toaster.success(`Narudžba #${order.id} je zaprimljena.`);this.destroyCard();this.form.controls.payment.setValue('CashOnDelivery');this.load();},error:()=>{this.submitting=false;this.toaster.error('Narudžbu nije moguće potvrditi. Provjerite dostupnost proizvoda.');}});}
}
