import { Component, OnInit, inject } from '@angular/core'; import { FormBuilder, Validators } from '@angular/forms'; import { UsersApiService } from '../../../api-services/users/users-api.service';
@Component({selector:'app-profile',standalone:false,template:`<section class="page"><h1>Moj profil</h1><img *ngIf="profileImageUrl" [src]="profileImageUrl" alt="Profilna slika" width="120"><label>Profilna slika (do 5 MB) <input type="file" accept="image/jpeg,image/png,image/webp,image/gif" (change)="uploadImage($event)"></label><form [formGroup]="form" (ngSubmit)="save()"><mat-form-field><mat-label>Ime</mat-label><input matInput formControlName="firstName"></mat-form-field><mat-form-field><mat-label>Prezime</mat-label><input matInput formControlName="lastName"></mat-form-field><mat-form-field><mat-label>Telefon</mat-label><input matInput formControlName="phoneNumber"></mat-form-field><button mat-raised-button color="primary" [disabled]="form.invalid">Sačuvaj profil</button></form><h2>Promjena lozinke</h2><form [formGroup]="passwordForm" (ngSubmit)="changePassword()"><mat-form-field><mat-label>Trenutna lozinka</mat-label><input matInput type="password" formControlName="currentPassword"></mat-form-field><mat-form-field><mat-label>Nova lozinka</mat-label><input matInput type="password" formControlName="newPassword"></mat-form-field><button mat-button [disabled]="passwordForm.invalid">Promijeni lozinku</button></form></section>`})
export class ProfileComponent implements OnInit {
  private fb=inject(FormBuilder); private api=inject(UsersApiService); profileImageUrl?:string;
  form=this.fb.group({firstName:['',[Validators.required]],lastName:['',[Validators.required]],phoneNumber:['']});
  passwordForm=this.fb.group({currentPassword:['',[Validators.required]],newPassword:['',[Validators.required,Validators.minLength(8)]]});
  ngOnInit(){this.api.getMe().subscribe(x=>{this.form.patchValue(x);this.profileImageUrl=x.profileImageUrl;});}
  uploadImage(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(file)this.api.updateProfileImage(file).subscribe(x=>this.profileImageUrl=x.profileImageUrl);}
  save(){if(this.form.invalid)return;this.api.updateMe({firstName:this.form.value.firstName!,lastName:this.form.value.lastName!,phoneNumber:this.form.value.phoneNumber ?? undefined}).subscribe();}
  changePassword(){if(this.passwordForm.invalid)return;this.api.changePassword({currentPassword:this.passwordForm.value.currentPassword!,newPassword:this.passwordForm.value.newPassword!}).subscribe(()=>this.passwordForm.reset());}
}
